package gui;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import controllers.ConnectionController;
import static controllers.ConnectionController.conectar;
import static controllers.ConnectionController.guardarDatosEnFichero;


public class ConfigConnection extends javax.swing.JDialog {
    
    App parent;

    /**
     * Creates new form ConfigurarConexion
     */
    public ConfigConnection(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = (App) parent;
        rellenarCampos();

    }

    private void rellenarCampos() {

        if (ConnectionController.getConector().equalsIgnoreCase("sqlite")) {
            comboboxConector.setSelectedIndex(0);
        } else if (ConnectionController.getConector().equalsIgnoreCase("derby")) {
            comboboxConector.setSelectedIndex(1);
        } else if (ConnectionController.getConector().equalsIgnoreCase("h2")) {
            comboboxConector.setSelectedIndex(2);
        }

        campoRuta.setText(ConnectionController.getRuta());
        campoPuerto.setText(String.valueOf(ConnectionController.getPuerto()));
        campoUsuario.setText(ConnectionController.getUsuario());
        campoContrasena.setText(ConnectionController.getContrasena());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboboxConector = new javax.swing.JComboBox<>();
        campoRuta = new javax.swing.JTextField();
        campoUsuario = new javax.swing.JTextField();
        campoContrasena = new javax.swing.JPasswordField();
        botonRestablecer = new javax.swing.JButton();
        botonProbarConexion = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        campoPuerto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurar conexión");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Base de datos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Ruta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel4, gridBagConstraints);

        comboboxConector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SQLite", "Derby", "H2" }));
        comboboxConector.setPreferredSize(new java.awt.Dimension(200, 25));
        comboboxConector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxConectorItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 5, 15);
        getContentPane().add(comboboxConector, gridBagConstraints);

        campoRuta.setText("src/databases/sqlite.db");
        campoRuta.setPreferredSize(new java.awt.Dimension(200, 25));
        campoRuta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoRutaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        getContentPane().add(campoRuta, gridBagConstraints);

        campoUsuario.setText("root");
        campoUsuario.setPreferredSize(new java.awt.Dimension(200, 25));
        campoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoUsuarioKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        getContentPane().add(campoUsuario, gridBagConstraints);

        campoContrasena.setPreferredSize(new java.awt.Dimension(200, 25));
        campoContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoContrasenaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        getContentPane().add(campoContrasena, gridBagConstraints);

        botonRestablecer.setText("Restablecer");
        botonRestablecer.setPreferredSize(new java.awt.Dimension(100, 25));
        botonRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestablecerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 5);
        getContentPane().add(botonRestablecer, gridBagConstraints);

        botonProbarConexion.setText("Probar conexión");
        botonProbarConexion.setPreferredSize(new java.awt.Dimension(150, 25));
        botonProbarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProbarConexionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 5);
        getContentPane().add(botonProbarConexion, gridBagConstraints);

        botonGuardar.setText("Guardar");
        botonGuardar.setEnabled(false);
        botonGuardar.setPreferredSize(new java.awt.Dimension(100, 25));
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 15);
        getContentPane().add(botonGuardar, gridBagConstraints);

        jLabel5.setText("Puerto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel5, gridBagConstraints);

        campoPuerto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPuertoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        getContentPane().add(campoPuerto, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        ConnectionController.setConector(comboboxConector.getSelectedItem().toString().toLowerCase());
        ConnectionController.setRuta(campoRuta.getText());
        ConnectionController.setPuerto(Integer.parseInt(campoPuerto.getText()));
        ConnectionController.setUsuario(campoUsuario.getText());
        ConnectionController.setContrasena(new String(campoContrasena.getPassword()));

        try {
            guardarDatosEnFichero();
        } catch (SQLException ex) {
            Logger.getLogger(ConfigConnection.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ConfigConnection.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            conectar();
            controllers.GeneralController.actualizarTablas(parent.getListaDTM(), parent.getListaLabels());
        } catch (SQLException ex) {
            Logger.getLogger(ConfigConnection.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonProbarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProbarConexionActionPerformed
        
        int puerto = 3306;
        try {
            puerto = Integer.parseInt(campoPuerto.getText());
        } catch (Exception ex) {
            
        }
        
        if (puerto < 0) {
            puerto = 3306;
        }

         if (new File(campoRuta.getText()).exists() || comboboxConector.getSelectedItem().toString().equals("H2")) {

            if (controllers.ConnectionController.probarConexion(
                    comboboxConector.getSelectedItem().toString().toLowerCase(),
                    campoRuta.getText(),
                    puerto,
                    campoUsuario.getText(),
                    new String(campoContrasena.getPassword()))) {
                campoPuerto.setText(String.valueOf(puerto));
                JOptionPane.showMessageDialog(this, "Conexión establecida.");
                botonGuardar.setEnabled(true);

            } else {

                JOptionPane.showMessageDialog(this, "No se pudo establecer la conexión.");
                botonGuardar.setEnabled(false);

            }
        } else {

            botonGuardar.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Por favor, escriba la ruta de un archivo de base de datos existente.");

        }
    }//GEN-LAST:event_botonProbarConexionActionPerformed

    private void restablecerDatosConexion() {
        String conectorSeleccionado = comboboxConector.getSelectedItem().toString().toLowerCase();

        switch (conectorSeleccionado) {
            case "sqlite":
                campoRuta.setText("src/databases/sqlite/sqlite.db");
                campoPuerto.setText("");
                campoUsuario.setText("");
                campoContrasena.setText("");
                break;
            case "derby":
                campoRuta.setText("src/databases/derby");
                campoPuerto.setText("");
                campoUsuario.setText("");
                campoContrasena.setText("");
                break;
            case "h2":
                campoRuta.setText("./src/databases/h2/h2");
                campoPuerto.setText("");
                campoUsuario.setText("sa");
                campoContrasena.setText("");
                break;
        }
    }

    private void botonRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestablecerActionPerformed

        restablecerDatosConexion();
    }//GEN-LAST:event_botonRestablecerActionPerformed

    private void comboboxConectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxConectorItemStateChanged
        botonGuardar.setEnabled(false);
        restablecerDatosConexion();
    }//GEN-LAST:event_comboboxConectorItemStateChanged

    private void campoRutaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRutaKeyTyped
        botonGuardar.setEnabled(false);
    }//GEN-LAST:event_campoRutaKeyTyped

    private void campoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUsuarioKeyTyped
        botonGuardar.setEnabled(false);
    }//GEN-LAST:event_campoUsuarioKeyTyped

    private void campoContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoContrasenaKeyTyped
        botonGuardar.setEnabled(false);
    }//GEN-LAST:event_campoContrasenaKeyTyped

    private void campoPuertoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPuertoKeyTyped
        botonGuardar.setEnabled(false);
    }//GEN-LAST:event_campoPuertoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConfigConnection dialog = new ConfigConnection(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonProbarConexion;
    private javax.swing.JButton botonRestablecer;
    private javax.swing.JPasswordField campoContrasena;
    private javax.swing.JTextField campoPuerto;
    private javax.swing.JTextField campoRuta;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JComboBox<String> comboboxConector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
