package gui;

import crud.CrudTruckers;
import crud.CrudCities;
import crud.CrudPackages;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import classes.Trucker;
import classes.City;
import classes.Package;


public class EditPackage extends javax.swing.JDialog {
    
    App app;

    /**
     * Creates new form AnadirEditarCamion
     */
    public EditPackage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        app = (App) parent;
        setTitle("Editar paquete");
    }
    
    private String antiguoCodigo;

    public void fijarDatos(Package paquete) throws SQLException {
        
        campoCodigo.setText(String.valueOf(paquete.getCodigopaquete()));
        antiguoCodigo = String.valueOf(paquete.getCodigopaquete());
        campoDescripcion.setText(paquete.getDescripcion());
        
        campoDestino.setText(String.valueOf(paquete.getDestino()));
        
        campoDireccionDestinatario.setText(paquete.getDirecciondestinatario());
        
        
        
        
        //Rellenar combo boxes con apartados y rfcs
        
        ArrayList<City> listaCiudades = CrudCities.leerTodos();
        
        String[] listaApartadosPostales = new String[listaCiudades.size()];
        
        for (int i = 0; i < listaApartadosPostales.length; i++) {
            listaApartadosPostales[i] = String.valueOf(listaCiudades.get(i)
                    .getApartadopostal() + " (" + listaCiudades.get(i).getNombre() + ")");
        }
        
        comboApartadoPostal.setModel(new javax.swing.DefaultComboBoxModel<>(listaApartadosPostales));
        
        ///////////////////////////////////////
        
         ArrayList<Trucker> listaCamioneros = CrudTruckers.leerTodos();
        
        String[] listaRFC = new String[listaCamioneros.size()];
        
        for (int i = 0; i < listaRFC.length; i++) {
            listaRFC[i] = String.valueOf(listaCamioneros.get(i).getRfc() + " (" 
                    + listaCamioneros.get(i).getNombre() + ")");
        }
        
        comboRFCCamionero.setModel(new javax.swing.DefaultComboBoxModel<>(listaRFC));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        campoDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoDestino = new javax.swing.JTextField();
        campoDireccionDestinatario = new javax.swing.JTextField();
        comboRFCCamionero = new javax.swing.JComboBox<>();
        comboApartadoPostal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Código:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 5, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Destino:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Dirección del destinatario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        getContentPane().add(jLabel4, gridBagConstraints);

        campoCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        campoCodigo.setEnabled(false);
        campoCodigo.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(25, 5, 5, 25);
        getContentPane().add(campoCodigo, gridBagConstraints);

        campoDescripcion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        campoDescripcion.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 25);
        getContentPane().add(campoDescripcion, gridBagConstraints);

        jLabel5.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        getContentPane().add(jLabel5, gridBagConstraints);

        jButton1.setText("Editar paquete");
        jButton1.setPreferredSize(new java.awt.Dimension(200, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 25, 25);
        getContentPane().add(jButton1, gridBagConstraints);

        jLabel6.setText("Apartado postal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        getContentPane().add(jLabel6, gridBagConstraints);

        jLabel7.setText("RFC (Camionero):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        getContentPane().add(jLabel7, gridBagConstraints);

        campoDestino.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        campoDestino.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 25);
        getContentPane().add(campoDestino, gridBagConstraints);

        campoDireccionDestinatario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        campoDireccionDestinatario.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 25);
        getContentPane().add(campoDireccionDestinatario, gridBagConstraints);

        comboRFCCamionero.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 25);
        getContentPane().add(comboRFCCamionero, gridBagConstraints);

        comboApartadoPostal.setPreferredSize(new java.awt.Dimension(200, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 25);
        getContentPane().add(comboApartadoPostal, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            if (campoCodigo.getText().isBlank() || campoDescripcion.getText().isBlank() 
                    || campoDestino.getText().isBlank()
                    || campoDireccionDestinatario.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos correctamente.");
            } else if (!campoCodigo.getText().toUpperCase().matches("\\d{1,6}")) {
                JOptionPane.showMessageDialog(null, "Inserte un código correcto (Numérico)");
            } else if (CrudPackages.comprobarExistencia(campoCodigo.getText())) {
                
                if (campoCodigo.getText().equals(antiguoCodigo)) {
                    ejecutarEdicion();
                } else {
                    JOptionPane.showMessageDialog(null, "Ya existe un paquete con el código '" 
                            + campoCodigo.getText() +"'.");
                }
                
            } else {
                ejecutarEdicion();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AddTruck.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ejecutarEdicion() throws SQLException {
        CrudPackages.actualizar(new Package(Integer.parseInt(
                campoCodigo.getText()), campoDescripcion.getText(), 
                campoDestino.getText(), campoDireccionDestinatario.getText(), 
                Integer.parseInt(comboApartadoPostal.getSelectedItem().toString().substring(0, 
                        comboApartadoPostal.getSelectedItem().toString().indexOf(" "))), 
                comboRFCCamionero.getSelectedItem().toString().substring(0, 
                        comboRFCCamionero.getSelectedItem().toString().indexOf(" "))), 
                antiguoCodigo);
                JOptionPane.showMessageDialog(null, "Datos editados correctamente.");
                app.actualizarTablas();
                dispose();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditPackage dialog = new EditPackage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoDescripcion;
    private javax.swing.JTextField campoDestino;
    private javax.swing.JTextField campoDireccionDestinatario;
    private javax.swing.JComboBox<String> comboApartadoPostal;
    private javax.swing.JComboBox<String> comboRFCCamionero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
