package gui;

import crud.CrudCities;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import classes.City;


public class EditCity extends javax.swing.JDialog {
    
    App app;

    /**
     * Creates new form AnadirEditarCamion
     */
    public EditCity(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        app = (App) parent;
        setTitle("Editar ciudad");
    }
    
    private String antiguoApartadoPostal;

    public void fijarDatos(City ciudad) {
        
        campoApartadoPostal.setText(String.valueOf(ciudad.getApartadopostal()));
        antiguoApartadoPostal = String.valueOf(ciudad.getApartadopostal());
        aprtadoNombre.setText(ciudad.getNombre());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        campoApartadoPostal = new javax.swing.JTextField();
        aprtadoNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Apartado postal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 5, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        campoApartadoPostal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoApartadoPostal.setPreferredSize(new java.awt.Dimension(175, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(25, 5, 5, 25);
        getContentPane().add(campoApartadoPostal, gridBagConstraints);

        aprtadoNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        aprtadoNombre.setPreferredSize(new java.awt.Dimension(175, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 25);
        getContentPane().add(aprtadoNombre, gridBagConstraints);

        jLabel5.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 25, 5, 5);
        getContentPane().add(jLabel5, gridBagConstraints);

        jButton1.setText("Editar ciudad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 25, 25);
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (campoApartadoPostal.getText().isBlank() || aprtadoNombre.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos correctamente.");
            } else if (!campoApartadoPostal.getText().matches("[1-9]\\d{1,4}")) {
                JOptionPane.showMessageDialog(null, "Inserte un apartado postal correcto (2 a 3 dígitos).");
            } else if (CrudCities.comprobarExistencia(campoApartadoPostal.getText())) {
                  if (campoApartadoPostal.getText().equals(antiguoApartadoPostal)) {
                    ejecutarEdicion();
                } else {
                    JOptionPane.showMessageDialog(null, "Ya existe una ciudad con apartado postal '" 
                            + campoApartadoPostal.getText() +"'.");
                }
            } else {      
                ejecutarEdicion();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AddTruck.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ejecutarEdicion() throws SQLException {
        City ciudad = new City(Integer.parseInt(campoApartadoPostal.getText()), aprtadoNombre.getText());  
                  CrudCities.actualizar(ciudad, antiguoApartadoPostal);
                JOptionPane.showMessageDialog(null, "Datos editados correctamente.");
                app.actualizarTablas();
                dispose();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditCity dialog = new EditCity(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aprtadoNombre;
    private javax.swing.JTextField campoApartadoPostal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
